# Generated by Django 6.0.4 on 2026-04-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_attendance_percent_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='attendance_percent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
    ]
