# Generated by Django 6.0.4 on 2026-04-21 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_attendance_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_percent',
            field=models.FloatField(default=95.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Marketing', 'Marketing')], default='IT', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='applied_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('ANNUAL', 'Annual Leave'), ('EMERGENCY', 'Emergency')], default='CASUAL', max_length=15),
        ),
    ]
